### ISSUE TITLE
Capitalization chaos

### ISSUE THREAD

**Issue by wolffg** [Team766/scouting-app#35]
In the web client:

You can create an account, and the userid field does not autocapitalize.  However, when signing in on mobile, web client auto-capitalizes userid field, and userid is case sensitive, so you get a password error, but you feel like you did it right
Mitigattgions: Don't autocapitalize userid field OR (probably best) userid should not be case sensitive

**Comment by JayAgra** [comment]
I think disabling autocapitalization on all fields would be simplest for now, but making `username` insensitive is something I can look into for later change.
